---
# tasks file for my_first_role

- name: install httpd
  yum:
    name: httpd
    state: present

- name: Start apache
  ansible.builtin.service:
    name: httpd
    state: started

- name: create index.html file
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: touch

- name: Write line in index.html file
  ansible.builtin.lineinfile:
    path: /var/www/html/index.html
    line: <h1>Hi from SkillStorm</h1>
    state: present